name: Copiar arquivos

on:
  push:
    branches:
      - develop

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Copiar arquivos 
        run: |
          cp deployDev/novo2.txt packageRelease/
          cp -R deployDev/novo2.txt packageRelease/
          cp -fR deployDev/novo2.txt packageRelease/             
          cp -uR deployDev/novo2.txt packageRelease/
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Criar artefato
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: deployDev/*.*

      - name: Baixar artefato
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: packageRelease/
          
      #- name: switching from HTTPS to SSH
      #  run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master    
