name: Copiar arquivos

on:
  push:
    branches:
      - actions-test

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Criar artefato
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: deployDev/*.*

      - name: Baixar artefato
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: packageRelease/
