name: Copiar arquivos

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Copiar arquivos 
        run: |
          cp deployDev/novo2.txt packageRelease/
          cp -R deployDev/novo2.txt packageRelease/
          cp -fR deployDev/novo2.txt packageRelease/             
          cp -uR deployDev/novo2.txt packageRelease/
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Criar artefato
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: deployDev/*.*

      - name: Baixar artefato
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: packageRelease/
          
      #- name: switching from HTTPS to SSH
      #  run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: |
          git add .
          git commit -m 'download of files'
      
      - name: outher identification
        if: ${{ github.actor == 'dependabot[bot]' }}
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      
      - name: user identification
        run: |
          git config --global user.email "awsbeluce@gmail.com"
          git config --global user.name "GuiBeluce"  
        
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      #- name: fetch from master
      #  run: git fetch origin master
      - name: push code to actions-test
        run: git push  
      
     
